locale: 'fr'

backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# Uncomment local_backend when you need to develop in your local
local_backend: true 
# run npx netlify-cms-proxy-server for local testing

media_folder: "static/assets" 
public_folder: "/assets" 

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/content/pages/index.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "index-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Tagline", name: "tagline", widget: "string"}
        - {label: "Featured Image", name: "featuredImage", widget: "image"}
        - {label: "Body", name: "body", widget: "markdown"}
        - label: "CTA"
          name: "cta"
          widget: "object"
          fields: 
            - name: "ctaText"
              label: "CTA text"
              widget: "string"
            - name: "ctaLink"
              label: "CTA Link"
              widget: "string"
      - label: "About"
        name: "about"
        file: "src/content/pages/about.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "about-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/about" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact"
        name: "contact"
        file: "src/content/pages/contact.md"
        fields:
        - {label: "Template", name: "template", widget: "hidden", default: "contact-page" }
        - {label: "Slug", name: "slug", widget: "hidden", default: "/contact" }
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  - name: Forms
    label: Formulaires
    label_singular: Formulaire
    description: Gérer les formulaires
    folder: "src/content/forms"
    slug: "/{{name}}"
    summary: "{{name}}"
    title: "{{name}}"
    create: true
    extension: json
    editor: {preview: false}
    fields: 
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'form'}
      - label: "Nom du formulaire"
        name: "slug"
        widget: "text"
      - label: "Texte avant le formulaire"
        name: "intro"
        widget: "text"
        required: false
      - label: "Champs"
        name: "fields"
        widget: "list"
        fields:
          - {label: Etiquette, name: label, widget: string}
          - label: Type
            name: type
            widget: select
            options:
              - { label: "Général (petit)", value: "input" }
              - { label: "Général (grand)", value: "textArea" }
              - { label: "Téléphone", value: "tel" }
              - { label: "Email", value: "email" }
              - { label: "Case à cocher", value: "checkbox" }
              - { label: "Nombre", value: "number" }
              - { label: "Couleur", value: "color" }
              - { label: "Adresse URL", value: "url" }
              - { label: "Date et heure", value: "datetime-local" }
              - { label: "Date", value: "date" }
              - { label: "Mois", value: "month" }
              - { label: "Semaine", value: "week" }
              - { label: "Heure", value: "time" }
              - { label: "Mot de passe", value: "password" }
      - label : "Texte après le formulaire"
        name: "outro"
        widget: "text"
        required: false
  - name: settings
    label: Settings
    files:
      - name: general
        label: General
        file: "src/util/site.json"
        fields:
          - label: meta
            name: meta
            widget: object
            fields:
              - widget: string
                name: title
                label: Site Title
                required: true
              - widget: string
                name: titleTemplate
                label: Title Template
                default: "%s"
                required: true
              - widget: string
                name: siteUrl
                label: Website URL
                required: true
              - widget: text
                name: description
                label: Description
                default: ''
                required: false
              - widget: image
                name: image
                label: image
                default: '/assets/stackrole.png'
              - widget: string
                name: twitterUsername
                label: Twitter
                required: false
          - label: "Google Analytics"
            name: ga
            widget: string
            hint: "Add you tracking ID, for example UA-XXXXXXXXX-X"
